apiVersion: v1
kind: Pod
metadata:
  name: addtaskmicroservice
  labels:
    name: addtaskmicroservice
spec:
  containers:
  - name: devopsinsider-addtaskmicroservice
    image: pawan7409/microaddtask
    ports:
    - containerPort: 8000
    env:
      - name: CONNECTION_STRING
        value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:seerver345657.database.windows.net,1433;Database=sql7869575;Uid=VM01;Pwd=Rjil@12345678;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
      
